### ISSUE TITLE
podman build fails

### ISSUE THREAD

**Issue by peshwar9** [capsule-corp-ternoa/ternoa-node#265]
`podman build -t tchain .` fails with: 

===
Default host: x86_64-unknown-linux-gnu
rustup home:  /root/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.63.0 (4b91a6ea7 2022-08-08)
--> 6679095c0f0
STEP 6/12: RUN git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git
Error: error building at STEP "RUN git submodule update --init --recursive": error while running runtime: exit status 128
===

**Comment by markopoloparadox** [comment]
@peshwar9 You need to clone the repo and then inside the repo do `podman build -t tchain .`
