### ISSUE TITLE
🧠 REFLEXION AROUND VALIDATORS 🧠

### ISSUE THREAD

**Issue by Tulleb** [capsule-corp-ternoa/ternoa-node#275]
## Why?

More and more waiting validators are giving up on becoming active someday, and end up unpluging their node.
Plus, there is less and less people willing to become a node validator since it's almost impossible (~17M CAPS actually needed as of today) to become active and effectively get rewarded.

## Today's current pain-points

- Only 8 different entities are running the total 15 active validators. It only represents 53% of decentralisation.
- Almost 100% of the current active validators have been active for months, getting 100% of the possible rewards.
- Validator in the waiting list does not earn anything at the moment. Including the ones waiting since the beginning of the main-net.

## Past mistakes

- June: When opening the main-net, it was told that we would switch to 30 validators within the end of June, and hopefully 60 within the end of the summer (sorry I don't have the source anymore).
- June: Mail from Guillaume to a node-enthusiasts newsletter proposing to nominate 2 specific nodes (MNSF-00 & MNSF-01) to get bonus APY; stabbing in the back validators from the waiting list.
- July: Switching from 10 validators to 15 because of Just-Mining arrival. Opening 5 new slots which were instantly taken by JM, killing hope of other validators already waiting for weeks.

## Proposed solutions

- Force a turn-over for all validators to become active at some point.
- Allow everyone to become active by ending the waiting list; splitting the rewards for everyone.

**Comment by Tulleb** [comment]
_Please guys, don't get me wrong reading this. I am really into Ternoa for more than a year now. And I just can't wait to send my first time capsules to my children at some point. I opened this thread as a post-mortem in order to help "us" improving, and hopefully not being forced to leave the ship as well._

-------

It's been a few months now that the mainnet has been launched, so it's easier to take a step back and analyse how nomination ended up with Ternoa's users.

Even though there are tutorials and advices everywhere regarding how to nominates nodes, as you can see, it's been months now that the 15 active validators did not rotate: meaning that **the current system is not working**.

-------

I would really like to know why we would/could not pick one of the 2 suggested solutions.

**- Why would an automatic turn-over be a mistake?**
**- What could go wrong if we automatically pass all waiting validators to active and share to rewards proportionally between them?**

From my point of view, I have one obvious answer and I'm afraid it the only one:

**- Because it does not profit (some of) the current 15 active validators**

whose, by the way, already received all the rewards from the past months, leaving nothing to others who just arrived a bit too late to the party.

-------

It's the 2nd time that it does happen, sadly. Last December, the ~25 minutes timing window to get one of the very few masternodes available on Just-Mining was a mistake. Frustrating a lot of your supporters who were all up for it.

**Ternoa is giving a LOT to only a FEW, for the second time now. Please don't repeat the same mistakes again.**

One of the recent tweet from the last ~20 waiting validators remaining:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/5658984/191695872-b35ceeee-268f-44fe-8e59-4a9a31f30de1.png">

> _FYI I am unplugging my node.
Currently unblocking the collateral.
3/4 months that I'm loosing money while being sure of never turning active (even for 24h). What a loss, have fun without me, and I'm quite sad writing these lines_

-------

One last thing, @Arn0-js could you elaborate your 2nd point please?
How do you qualify this email from [Guillaume Gabriel (Support Manager @Ternoa)](https://www.linkedin.com/in/guigabriel) if not "interference" as encouraging nominators to change their nominees:
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/5658984/191698728-1f0e5b49-c1db-4639-9c65-81c123d08a33.png">

-------

**Comment by 0x2nm** [comment]
I’ll first try to answer your questions, then address concerns raised.
 
**Q) Why would an automatic turn-over be a mistake?**
 
An automatic turn-over would entirely defeat the purpose of Nominated Proof-of-stake.

The goal of NPoS isn’t to ensure a fair distribution of rewards across ALL participants, but rather to ensure only the most efficient validators are picked, for the sake of network stability.
 

**Q) What could go wrong if we automatically pass all waiting validators to active and share to rewards proportionally between them?**
 
This decision creates many issues:
1) 	It would decrease APR for validators. Hence it would most likely deter any qualified and reliable validator to come and secure our network.
2) 	It would not make sense from a blockchain sizing perspective. Our goal, as an entity, is to bring Ternoa chain safely to full decentralization. We are careful about maintaining a balance between network growth and decentralization.
3) It would create a risk that unreliable nodes become validators, hence jeopardising network stability.
4) It would open the door to a worst case scenario where any medium-sized CAPS holder could create a large number of validators and take control of the network either directly or through collusion.
 
 
**Concerns regarding “certainty to never enter the active set”**
 
Nomination ensures there is no “certainty” re. active set participants. However, entering the active set requires efforts in terms of maintaining a reliable validator, advertising it, and educating community about how to make best possible nominations on their end.
 
 
**Concerns regarding “interference to change nominees”**

This email was sent to a limited number (c. 100) of CAPS holders that had participated in Q1 2022 to a program designed to support mainnet launch. 

To incentivize and reward their commitment to be early validators (hence taking more risks, for the good of the entire community), Marketing funds have been allocated to offer guaranteed top-up rewards to these pioneers. This program has always been fully disclosed to the entire community.
 
**Concerns regarding active set growth**

Active set size increases with blockchain use, and total validators running. With recent network developments, an increase of both active set and rewards is currently planned on the tech committee’s schedule.


**In a nutshell:**

**Ternoa is an ambitious chain with a long term vision.  No decision is made to favour any entity or validator over the other. However some validators seem to have become more proficient in using NPoS to their economical advantage. We can only encourage all validators to do their best to join the active set.**


**We only have one goal: creating a stable and decentralized network. NPoS is a very powerful tool to achieve this endeavor, and we are convinced it’s the most efficient validators election process available.**


**We are lucky to be in a position to make enlightened decisions, thanks to experiences and feedbacks from earlier layer 1s, and polkadot/the parity ecosystem.**

**Comment by Tulleb** [comment]
Thank you for your answer Martin, I appreciate the time you took for it. But honestly, if you only read half of my messages, don't bother at all next time.

I already said everything that had to be said. I will just insist on a few reminders, in case you don't have time to go through what I wrote...

-------

### ~180M$ and a good 24/7 uptime machine.

This is what you need today to become an active validator. Good luck gathering it through *"maintaining, advertising, and educating efforts"*.

-------

You said passing everyone to active validator *"would not make sense from a blockchain sizing perspective"*.
It's sad we don't have any other **massive** blockchain project to take as a great [example](https://launchpad.ethereum.org/) for that...

-------

> It would open the door to a worst case scenario where any medium-sized CAPS holder could create a large number of validators and take control of the network either directly or through collusion.

At the moment, there are 8 nodes (more than 51%) belonging to only 2 people: Louis_Crypté and Hasheur.

So right now, with the current NPoS system, can you tell me what would happen if tomorrow morning, Louis calls Owen proposing him to cashout all Ternoa's market cap within the end of the next era?

### Would they be able to do that?

Damn I hope they are not reading me... 🙄

-------

**NPoS is exactly what you should drop right now for a more decentralised system.**

Keeping this current pro-NPoS mindset can only means 2 things: either you are either not up for the task, or you have some kind of shady "staying active validator" deal(s) you can't speak about.

**Comment by peshwar9** [comment]
@Tulleb : You seem to be comparing a Substrate Solo-chain which is a few months old to Ethereum. Even if were to take your own argument, soon after the merge these were the stats: You'll notice that just these three entities can control ethereum's governance. My point is not to belittle the huge efforts of Ethereum team, but just highlighting that this is a hard problem to solve. 

![eth-pos](https://user-images.githubusercontent.com/7454729/192088168-dd15489b-e5f5-4b7a-b0ee-9d8facb6f468.jpeg)

Specifically for Ternoa, we have already mentioned that in the initial stages of the network, we will need to enlist support from experienced validators, and progressively the decentralisation will improve. This plan is very much alive and you will continue to see us progressively increase the active validator set.

Further, it is very important for you to remember that Ternoa has adopted Polkadot's NPOS consensus for deterministic finality, and the finalized blocks can NOT be reverted, unlike chains that have adopted probabilistic finality. 
While I appreciate your concerns, I wanted to assure you that all these aspects around risk of validator diversity were discussed even before we launched the mainnet, I hope you understand that decentralisation is a journey , and you will continue to see us move towards this goal (even beyond just validator diversity).

**Comment by 0x2nm** [comment]
@Tulleb all of your messages had been read, and I decided to only answer questions, or explicit concerns (and not innuendos nor assumptions). I’ll gladly answer any remaining questions you have, as long as they are brought up in a constructive way.

**Re. impossibility to become a validator**

Where did you get the 180 m$ figure from ? Staking requirement is 150k CAPS today on ternoa chain. It is therefore possible for anybody managing to gather a strong enough community to enter the active set.

**Re. ETH as an example** 

Ethereum PoS is an interesting example, but I’d like to add two pieces of information in addition to @peshwar9's answer:

- First, we’re talking about the very specific case of a large scale PoW network switching to PoS. Both network and community maturity can hardly be compared with our situation as a young infrastructure. Hence I reiterate my point, getting 60+ validators in our activeset would not make sense today.

- Let’s not forget that in spite of ETH maturity, massive concerns were raised due to the fact 3 centralized US-based operators were controlling a large majority of validators after the merge.

**Re. NPoS and risks of collusion**

First of all, controlling 51% of the stake wouldn’t put validators in a position to steal funds. And nomination is exactly designed so that all holders can decide who controls the stake. Hence, efforts required to educate the community, making sure nominators play their role limiting centralization. Based on current nominations, we can only assume that most holders favor stability VS. decentralization. 

Just Mining is a company. Their business is to operate nodes on behalf of their clients. They’ve got no interest at all in colluding to compromise the chain integrity. This would go against their clients’, and their own interest. While your doomsday scenario could theoretically be valid, it implies that large operators would go full suicide-bomb mode for the sake of killing ternoa chain, which makes little sense. This is part of the game theory fundamentals underlying NPoS mechanisms.

“Just-Mining nodes” do not belong to an individual. They are nodes operated by Just Mining, on behalf of their clients. While we would obviously prefer that all these CAPS holders were nominating validators without help of Just-Mining, we are glad that professional operators help secure the network by bringing best-in-class devops, for the interest of their own clients. Our goal is to keep growing the network so that centralized operators have a harder time competing with independent operators. 

**Regarding your conclusion and last statement:**

As a fully open source blockchain, we are well aware that our decisions are under scrutiny. Because you are free to think that we “are not up for the task”, we are grateful to be counting on chain governance instances to help guide the chain’s evolution. These instances are open to all stakeholders and they are able to make proposals that can then be implemented by the chain.

Last but not least: there are no sort of “staying active validator” deals in place, with any operator. Accusing us of “shady (...) deals” is plain and simple defamatory, and harmful to ternoa, ecosystem, and stakeholders’ interests.

**Comment by Tulleb** [comment]
Thank you @peshwar9 for your answer.

So if I get this right, no possible 51% attack thanks to NPoS? I'm way less an expert than you, so I trust what I'm being told.

Hopefully things will change soon and the number of validators will go back increasing.
It's just that the *journey* is looking a bit frozen lately, and it's quite frustrating to watch.

**Comment by peshwar9** [comment]
@Tulleb Yeah,  PoW networks (such as Bitcoin or Eth classic) are vulnerable to 51% attacks, which occur when a group of miners control the consensus with more than half of the mining hashrate. But Ternoa uses a BFT-based NPOS algorithm that requires over 2/3rs of total network stake to come together if they'd like to cause any damage. But it would be very expensive to mount such an attack, they would have to risk slashing of their staked tokens, and even then any damage would be limited to blocks after the last finalized block.
So, TL;Dr, there are many protections in place, thanks to the great work done by the Polkadot engineering team, and the additional network governance checks and balances Ternoa has introduced additionally.
But I sense your frustration, and maybe we have to do a better job of communicating. Point well noted.

**Comment by Tulleb** [comment]
Thank you as well @0x2nm for your time.

> Where did you get the 180 m$ figure from ?

180K$*, sorry for the typo. I edited the previous message.
17M CAPS actually needed at the moment to become active: so 17M x 0.011$ = ~180K$.

> Last but not least: there are no sort of “staying active validator” deals in place, with any operator. Accusing us of “shady (...) deals” is plain and simple defamatory, and harmful to ternoa, ecosystem, and stakeholders’ interests.

Sorry for the FUD, and I feel even more sorry since I really trust in Ternoa. But it's been a long way if I am ending up thinking this kind of stuff. Please, just try to forget about your position for just a minute and put yourself in my shoes:

1. You follow the project for a very long time now. Really see yourself into it and sharing it to all your crypto friends.
2. You patiently wait for Just-Mining partnership to start a masternode in December 2021.
3. It's D-day! The calendar is set, wallet is ready, but you miss the opportunity because there was actually just a very few nodes available.
4. You are told that more masternodes will arrive in January.
5. January pass... February too... [**"News coming soon!"** I am being told](https://www.reddit.com/r/Ternoa_/comments/sewpd2/new_masternodes_anytime_soon/). 
6. Finally June arrives with the mainnet! You purchase your computer, mount everything and at the end you realise that there are only 8 active nodes receiving rewards, ordered by who has the most staked CAPS. You are 11th in the list with your ~200K CAPS.
7. It's OK, it's NPoS! *Anybody could turn active by being nominated by others!* But then, even though you **do** put a lot of efforts into communication, you understand that most of the new nominators always nominate most of the active nodes without knowing anything about what is NPoS; comforting the lead of the 8 already at the top.
8. I realise meanwhile that some of the top-8 lucky ones are actually only a few people who possess several active nodes. OK but what about decentralisation? Is it not what you are trying to achieve here?
9. Well, even though it does not look very fair, you keep having big hopes because as the team said, you should reach 30 active nominators very soon, and you trust them, again!
10. "Good" news! The list finally passes to 15 slots, wow! Not the 30 you expected but let's take it! Oh wait... what is that? 5 new Just-Mining nodes arriving **the exact same day** with the biggest stake out there! Obviously, they take 5 of the 7 fresh slots. Sadly you are not big enough to take one of the only 2 remaining new slots.
11. July arrives. Maybe some more active slots? No. Instead you receive an email from Ternoa literally stabbing you in the back; proposing their mailing list to join 2 new nodes which are not even running yet in exchange of extra CAPS rewards. OK... Well... How should you react?
12. For your own sake, you decide to take a step back from the community. Your node is still running. Alerts are on in case it turns off. Automatisations to upgrade the system and its security are still in place. You are still secretly wishing for the day you might see yourself in the active list, with this precious green check at the left of your node's name.
13. July passes, August as well...
14. We are now end of Septembre. You receive a tweet alert from Ternoa: "become a validator". What a joke! Are they serious? How can they still dare saying that? What's the purpose? You take a look at the comments: 1/3 common scam automatic replies, 1/3 of "congratulations you are so great", and one last third were actually... **people like you**! Wow! You were only thinking it was all bad luck so far, but no! You are not alone!
15. You go back to the mainnet dashboard: and indeed, you went from 60+ validators end of June to barely 40+ now! 30% of the validators unplugged their machines and gave up on Ternoa! **30%!** ***Thirty percent!***
16. It's today. You are putting your last Ternoa's hope on this thread. Hopefully opening the eyes of the team regarding the current situation, somehow.
17. The team address your concern by confirming that NPoS is the way to go. That the current active list of 8 people (companies if you prefer) out of 15 slots, nor the fact than 1 single physical person gets 20% of the active nodes, are not a problem at all regarding decentralisation. That the -30% of validators is not an issue and that everything's fine right now.

-------

**18. You end up with only two possible explanations in your mind: either the team is not up to the task, or there is some kind of arrangement you don't know about to let some of the 8 people gets most of the rewards for as long as possible.**

![Untitled](https://user-images.githubusercontent.com/5658984/192093499-d475a03b-2c65-4c6f-8d5c-ab3b0aa6b0c0.jpg)

**Comment by janinp** [comment]
So disappointed, so sad and so much in line with you Tulleb! Waiting since the beginning of mainnet. Suffered a significant loss with the drop in Caps value of course. Still paying for the VPS every month for nothing. Wow. Difficult to keep being a promoter. I do not how’ve the time nor the ressources to build a community around my ternoa move. I guess I will have to give up as well.

**Comment by Tulleb** [comment]
FYI I just unplugged my node today. End of my 2-years Ternoa adventure.

I wish you all the best guys, especially to whoever would still dare to become a node operator now.
