### ISSUE TITLE
linker `cc` not found

### ISSUE THREAD

**Issue by Tulleb** [capsule-corp-ternoa/ternoa-node#277]
Error while trying to compile the [1.1.0](https://github.com/capsule-corp-ternoa/ternoa-node/archive/refs/tags/v1.1.0.tar.gz) source code through `cargo build --locked --release`:

```
   Compiling proc-macro2 v1.0.36
   Compiling syn v1.0.89
   Compiling libc v0.2.121
   Compiling memchr v2.4.1
   Compiling serde_derive v1.0.136
   Compiling typenum v1.15.0
   Compiling serde v1.0.136
   Compiling log v0.4.16
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)

error: could not compile `log` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by markopoloparadox** [comment]
Hello

What operating system are you running? Did you install all the dependencies?
This error on Ubuntu systems is tied not having "build-essential" packages installed.

**Comment by markopoloparadox** [comment]
After reading your other issues, is seems like that you are trying to use the latest documentation with old commit of this repo. If you want to use an older commit I would suggest you to use the readme version of that commit.
