### ISSUE TITLE
Deprecated latest-mainnet branch

### ISSUE THREAD

**Issue by Tulleb** [capsule-corp-ternoa/ternoa-node#278]
Your `latest-mainnet` branch lead to the 1.0.0 version README which still contains link to the https://ternoa-2.gitbook.io/testnet-2/v/ternoa-cli/ documentation, instead of the https://docs.ternoa.network/ official one.

Anyway I guess it should now lead to the 1.1.0 version commit, or just be deleted.

Trying to update my node for 1.0.0 to 1.1.0 and it's been about 1 hour I am looking for informations at the moment. Just giving you my feedback for further improvements.

**Comment by markopoloparadox** [comment]
Hello

Good catch!
Both release-X branches are not used anymore. The good part is that I don't think anyone knows that those branches exist at all since they are not mentioned in any official Mainnet or Alphanet docs.
