### ISSUE TITLE
DevOps: Redeploy Alphanet

### ISSUE THREAD

**Issue by markopoloparadox** [capsule-corp-ternoa/ternoa-node#281]
Tasks todo:
- Generate new Chain Specification for Alphanet
- Configure VMs
- Release a new version of Ternoa Node

We need to make sure that what ever we do here that we record and/or live stream it. Currently there is no documentation on how to fully deploy a chain and we need to fix that.

People who are responsible for this task: @soufiane-bouchaara @Leouarz @markopoloparadox

**Comment by ogous** [comment]
@markopoloparadox is this related that Alphanet transactions are not working at the moment? Or should I open a new issue about it?
